### ISSUE TITLE
Add animal gallery (browsing)

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#1]
## Value statement - a requirement, not a solution
As a user
I need an list of cards
so that see which dogs are available
## Description (Text, Scribble, Wireframe, Design)
![card list](https://i.imgur.com/MmkfAUI.png)
## Acceptance criteria
- [x] Cards have to be separated
- [x] Picture has to have a good size
- [x] Text has to be in a goo readable size
- [x] Cards are scrolled vertically
## Tasks
- [x] Make a cards.json to have some data to display
- [x] Create necessary components
- [x] Styling
- [x] Test in mobile and desktop view
## Size
medium
