### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#10]
## Value statement - a requirement, not a solution
As a user
I need a navigation bar
so that I'm able to move between pages
## Acceptance criteria
- [ ] Navbar is shown
- [ ] Navbar is clickable
- [ ] Navbar leads at least to gallery
## Tasks
- [ ] Build navbar
- [ ] Style navbar
- [ ] Check if other components are still in position
- [ ] Test on mobile and desktop
## Size
medium
