### ISSUE TITLE
Add backend (firebase?)

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#12]
## Value statement - a requirement, not a solution
As a user
I want to save my settings
so that I can use the app on different devices
## Acceptance criteria
- [x] Settings are saved to database
- [x] Settings are loaded from database
## Tasks
- [x] Implement a database e.g. firebase
- [x] Add saving and loading functions 
## Size
large
