### ISSUE TITLE
Add profile for animal shelters

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#13]
## Value statement - a requirement, not a solution
As a animal shelter 
I need a profile 
so that users can contact us
## Description (Text, Scribble, Wireframe, Design)
See dog profile
## Acceptance criteria
- [ ] Animal Shelter profile exists and is fully functional
- [ ] Profile is linked on the sidenav
- [ ] Profile has a decent style
## Tasks
- [ ] Add new profile page for animal shelters
- [ ] Make/Use profile component
- [ ] Add styling
- [ ] Test on mobile and desktop
## Size
medium/large
