### ISSUE TITLE
Add User profile

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#14]
## Value statement - a requirement, not a solution
As a user
I need a profile
so that I can provide different information about myself and my living situation for example
## Description (Text, Scribble, Wireframe, Design)
Similar to animal shelter profile page
## Acceptance criteria
- [x] Profile page is visible and fully functional
- [x] Profile page is linked in sidenav
## Tasks
- [x] Make/Add profile component
- [x] Add styling
- [x] Add upload button for pictures
- [x] Add simple functionalities to upload feature
- [x] Test on mobile and desktop
## Size
large
