### ISSUE TITLE
Add search bar (fuzzy + exact search) aka filter

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#15]
## Value statement - a requirement, not a solution
As a user
I need a search
so that I can find my favorite dog
## Description (Text, Scribble, Wireframe, Design)
![searchbar](https://i.imgur.com/h9qHZeF.png)
## Acceptance criteria
- [x] Search is fixed in top bar
- [x] Search has two modes (fuzzy + exact)
- [x] One can reach the search though the sidebar
## Tasks
- [x] Add fuzzy search function
- [x] Add placeholder text
- [x] Add styling
- [x] Test on mobile and desktop
## Size
extra large
