### ISSUE TITLE
Add Chat

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#18]
## Value statement - a requirement, not a solution
As a user  
I need an chat
so that I have a faster communication channel with shelters
## Acceptance criteria
- [ ] One can send a message
- [ ] Message is visible in chat window/site
- [ ] Simple styling
## Tasks
- [ ] Implement API for chat
- [ ] Add chat history
- [ ] Add styling
- [ ] Test on mobile and desktop
## Size
large
