### ISSUE TITLE
Add Login

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#19]
## Value statement - a requirement, not a solution
As a user
I need a way to keep all my settings and chats together
so that I don't need to change my settings every time I open the app
## Acceptance criteria
- [x] A login page
- [x] Field for username/email and password
- [x] Simple stying
## Tasks
- [x] Add new page
- [x] Create a form with two inputs and one button
- [x] Create some kind of hash key to keep user logged in
- [x] Save hash key to device as cookie(?)
## Size
medium
