### ISSUE TITLE
Single card with details (new page)

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#2]
## Value statement - a requirement, not a solution
As a user
I want to see details of the dog
so I it's easier to make a decision or get in contact with the animal shelter
## Description (Text, Scribble, Wireframe, Design)
![design](https://i.imgur.com/9U5akWd.png)
## Acceptance criteria
- [x] Dog is displayed on new page
- [x] Details and photo are visible, centered and scrollable
## Todo
- [x] Add onClick to each card
- [x] Add a new page to display photos and description
- [x] Make the content scrollable
- [x] Style
- [x] Test on mobile and desktop
## Size
large
