### ISSUE TITLE
Add Registration

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#20]
## Value statement - a requirement, not a solution
As a user
I need to register myself
so that I have my own account with all my settings
## Acceptance criteria
- [x] A Registration page
- [x] Simple form
- [x] Some styling
## Tasks
- [x] Add registration page
- [x] Add new form with two input fields for email and password
- [x] Save email and password to database and hash them
- [x] Add styling
- [x] Test on mobile and dekstop
## Size
medium
