### ISSUE TITLE
Add google maps to modal

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#3]
## Value statement - a requirement, not a solution
As a user
I need an map
so that I know where the animal shelter is
## Description (Text, Scribble, Wireframe, Design)
Map from Google implemented into modal
## Acceptance criteria
- [ ] Map is shown on the lower part of each card modal
- [ ] Map is interactive
- [ ] Map shows random place
## Tasks
- [ ] Implement google maps api
- [ ] Add map to the bottom of modal
- [ ] Minor styling
- [ ] Test on mobile and desktop
## Size
small
