### ISSUE TITLE
Add contact form for user

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#5]
## Value statement - a requirement, not a solution
As a user 
I need a way to get in contact with the animal shelter
so that I'm able to make an appointment
## Description (Text, Scribble, Wireframe, Design)
Form
## Acceptance criteria
- [ ] Form is visible and has a minimal style
- [ ] Form does not reload the page
- [ ] Form resets after submit 
- [ ] A pop up is displayed to show that the form was successfully submitted
## Tasks
- [ ] Build form (title, email, name, text, phone)
- [ ] Prevent reload
- [ ] Reset form after submit
- [ ] Add pop up to display successful submit
- [ ] Add style
- [ ] Test on mobile and desktop
## Size
medium
