### ISSUE TITLE
Create image gallery/slider on animal profile

### ISSUE THREAD

**Issue by kdcho** [kdcho/petster#7]
## Value statement - a requirement, not a solution
As a user
I need to see more than one picture
so that I can see the animal in different situations
## Description (Text, Scribble, Wireframe, Design)
![awesome-slider](https://i.imgur.com/EvRPIBh.png)
## Acceptance criteria
- [x] Slider is shown
- [x] Slider shows multiple images
- [x] Slider slides to left and right
## Tasks
- [x] Implement awesome slider
- [x] Add/Display images from database
- [x] Style slider
- [x] Test slider on mobile and desktop
## Size
medium
